name: Terraform Pipeline
on: workflow_dispatch

jobs:
  infra:
    name: Terraform Init Plan Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Load SPN Secret to ENV
        run: echo "${{ secrets.SPN }}" >> $GITHUB_ENV

      - name: Azure Login
        run: |
          az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID"
          az account set -s "$ARM_SUBSCRIPTION_ID"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -no-color
